" Make sure Vim-Plug is installed
if empty(glob("~/.vim/autoload/plug.vim"))
    execute '!curl -fLo ~/.vim/autoload/plug.vim'
    \ 'https://raw.github.com/junegunn/vim-plug/master/plug.vim'
endif

" =====
" Start Vim-Plug
" =====
call plug#begin('~/.vim/plugged')

" LightLine: A light and configurable statusline/tabline plugin for Vim
Plug 'itchyny/lightline.vim'

" Dracula theme
Plug 'dracula/vim', { 'as': 'dracula' }

" Onehalf theme
Plug 'sonph/onehalf', {'rtp': 'vim/'}

call plug#end()

" =====
" General settings
" =====

" Fix of linelight
set laststatus=2
set noshowmode

" Syntax highlighting
syntax on

" Fix colours?
let g:dracula_colorterm = 0
" set termguicolors
set t_Co=256
if &term =~ '256color'
  set t_ut=
endif
if $COLORTERM=~"truecolor"
  set termguicolors
endif

" Dracula theme
" color dracula

" Set Onehalf theme
colorscheme onehalfdark
let g:airline_theme='onehalfdark'

" File type recofnition
filetype on

" Line Numbers
set number

" Fix backspace
set backspace=indent,eol,start
