# iPath to your oh-my-zsh installation.
export ZSH="/Users/mwatkins/.oh-my-zsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="simple"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  virtualenv
  zsh-completions
  zsh-syntax-highlighting
  zsh-autosuggestions
)

# Aliases
alias history="history 1"
alias plzbrew="sudo chown -R $(whoami) /usr/local/bin /usr/local/lib /usr/local/sbin && chmod u+w /usr/local/bin /usr/local/lib /usr/local/sbin"

source $ZSH/oh-my-zsh.sh
